# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-25 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.CharField(max_length=100)),
                ('political_party', models.CharField(max_length=100)),
                ('quote', models.CharField(max_length=500)),
                ('photo', models.CharField(max_length=1000)),
            ],
        ),
    ]
